/* WORDS SELECT */
--SHOW PART OF THE RECORDS
SELECT COUNT(*) FROM WORDS;
SELECT * FROM WORDS WHERE id > 890;
SELECT * FROM WORDS WHERE id > 1410;
SELECT * FROM WORDS WHERE id > 539; -- words around the word of query

SELECT * FROM WORDS WHERE word LIKE '%blow%';
SELECT * FROM WORDS WHERE collins_meaning LIKE '%呼啸%';
SELECT * FROM WORDS WHERE episode = 'FS01E06';

/* COCA60000 SELECT */
SELECT * FROM COCA60000 WHERE word = 'don''t';

/* WORDS_COCA SELECT */
SELECT * FROM WORDS_COCA WHERE word = 'diarrhea';
-- SELECT * FROM WORDS_COCA ORDER BY COCA, word, collins_meaning;  -- For REVISE

-- FOR REVISE every day
SELECT * FROM (
    SELECT * FROM (
        SELECT * FROM WORDS_COCA WHERE COCA IS NOT NULL ORDER BY COCA, collins_meaning)    -- FOR WORDS
    UNION ALL
    SELECT * FROM (
        SELECT * FROM WORDS_COCA WHERE COCA IS NULL AND word <> '-' ORDER BY word, collins_meaning)    -- FOR PHRASE put similar phrases together
    UNION ALL
    SELECT * FROM (
        SELECT * FROM WORDS_COCA WHERE COCA IS NULL AND word = '-' ORDER BY episode))      -- FOR SENTENCE
WHERE id > 1410;

-- FOR REVISE ALL
SELECT * FROM (
    SELECT * FROM WORDS_COCA WHERE COCA IS NOT NULL ORDER BY COCA, collins_meaning)    -- FOR WORDS
UNION ALL
SELECT * FROM (
    SELECT * FROM WORDS_COCA WHERE COCA IS NULL AND word <> '-' ORDER BY word, collins_meaning)    -- FOR PHRASE put similar phrases together
UNION ALL
SELECT * FROM (
    SELECT * FROM WORDS_COCA WHERE COCA IS NULL AND word = '-' ORDER BY episode);      -- FOR SENTENCE