/* WORDS SELECT*/
--SHOW PART OF THE RECORDS
SELECT * FROM WORDS WHERE id > 530;
SELECT * FROM WORDS WHERE id > 710;
SELECT * FROM WORDS WHERE word = 'gross out';
SELECT * FROM WORDS WHERE episode = 'FS01E06';

/* COCA60000 SELECT*/
SELECT * FROM COCA60000 WHERE word = 'umami';

/* WORDS_COCA SELECT*/
SELECT * FROM WORDS_COCA WHERE word = 'earth';
