/* WORDS SELECT*/
--SHOW PART OF THE RECORDS
SELECT * FROM WORDS WHERE id > 530;
SELECT * FROM WORDS WHERE word = 'drill';
SELECT * FROM WORDS WHERE episode = 'Other';

/* COCA60000 SELECT*/
SELECT * FROM COCA60000 WHERE word = 'egypt';

/* WORDS_COCA SELECT*/
SELECT * FROM WORDS_COCA WHERE word = 'corridor';
